---
abstract: 'command line interface to access Dropbox API'
author:
  - '- Shinichiro Aska'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.2, CPAN::Meta::Converter version 2.132661'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-dropboxapi
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  App::dropboxapi:
    file: lib/App/dropboxapi.pm
    version: 1.17
requires:
  DateTime::Format::Strptime: 0
  Encode::Locale: 0
  Encode::UTF8Mac: 0
  JSON: 0
  Path::Class: 0.26
  WebService::Dropbox: 1.17
  perl: 5.008001
resources:
  bugtracker: https://github.com/s-aska/dropbox-api-command/issues
  homepage: https://github.com/s-aska/dropbox-api-command
  repository: git://github.com/s-aska/dropbox-api-command.git
version: 1.17
x_authority: cpan:ASKADNA
x_contributors:
  - 'Sylvain Filteau <cidsphere@gmail.com>'
  - 'aska <aska@www5009u.sakura.ne.jp>'
  - 'Andrew Childs <lorne@cons.org.nz>'
  - 'Shinichiro Aska <s.aska.org@gmail.com>'
  - 'aska <aska@linecorp.com>'
