---
abstract: 'Dropbox API Wrapper Command.'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-dropboxapi
no_index:
  directory:
    - t
    - inc
requires:
  DateTime::Format::Strptime: 0
  Encode::Locale: 0
  Encode::UTF8Mac: 0
  ExtUtils::Install: 1.43
  ExtUtils::MakeMaker: 6.3
  JSON: 0
  Path::Class: 0.26
  WebService::Dropbox: 1.15
version: 1.07
